Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -45,10 +45,10 @@ echo "-----> Building Racket Runtime Environment"
 
 RACKET_DIR=$(build_racket $(get_racket $(make_tempdir racket)))
 
-if [ ! -d $RACKET_DIR ] then
-  echo "Fail" | indent
-  exit 1
-fi
+#if [ ! -d $RACKET_DIR ] then
+#  echo "Fail" | indent
+#  exit 1
+#fi
 
 echo "-----> Creating racketapp From app.rkt"
 cd $RACKET_DIR
